[package]
name = "gl_types"
description = "Provides the types for OpenGL and OpenGL ES."
repository = "https://github.com/Lokathor/gl_types/"
version = "0.1.0"
edition = "2021"
license = "Zlib OR Apache-2.0 OR MIT"
